services:
  app:
    build: .
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: >
      /bin/sh -c "
        # Run migrations
        python manage.py migrate --noinput;
        python manage.py collectstatic;
        # Start the Django app with Gunicorn
        exec gunicorn -b 0.0.0.0:8000 myproject.wsgi
      "
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 2545
      POSTGRES_DB: timetracker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: