# Generated by Django 5.2.1 on 2025-05-21 07:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="worked_hours",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Hours Worked",
            ),
        ),
    ]
